// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: from-manager.proto

package undo.proto;

public final class FromManagerProto {
  private FromManagerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ToDataNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 newCommit = 1;
    /**
     * <code>optional int64 newCommit = 1;</code>
     */
    boolean hasNewCommit();
    /**
     * <code>optional int64 newCommit = 1;</code>
     */
    long getNewCommit();

    // optional bool resetDependencies = 2;
    /**
     * <code>optional bool resetDependencies = 2;</code>
     */
    boolean hasResetDependencies();
    /**
     * <code>optional bool resetDependencies = 2;</code>
     */
    boolean getResetDependencies();

    // optional bool redoOver = 3;
    /**
     * <code>optional bool redoOver = 3;</code>
     */
    boolean hasRedoOver();
    /**
     * <code>optional bool redoOver = 3;</code>
     */
    boolean getRedoOver();

    // repeated int32 pathBranch = 4;
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    java.util.List<java.lang.Integer> getPathBranchList();
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    int getPathBranchCount();
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    int getPathBranch(int index);

    // repeated int64 pathCommit = 5;
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    java.util.List<java.lang.Long> getPathCommitList();
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    int getPathCommitCount();
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    long getPathCommit(int index);
  }
  /**
   * Protobuf type {@code voldemort.ToDataNode}
   *
   * <pre>
   *To data node
   * </pre>
   */
  public static final class ToDataNode extends
      com.google.protobuf.GeneratedMessage
      implements ToDataNodeOrBuilder {
    // Use ToDataNode.newBuilder() to construct.
    private ToDataNode(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ToDataNode(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ToDataNode defaultInstance;
    public static ToDataNode getDefaultInstance() {
      return defaultInstance;
    }

    public ToDataNode getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ToDataNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newCommit_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              resetDependencies_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              redoOver_ = input.readBool();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                pathBranch_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              pathBranch_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                pathBranch_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                pathBranch_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                pathCommit_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              pathCommit_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                pathCommit_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                pathCommit_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          pathBranch_ = java.util.Collections.unmodifiableList(pathBranch_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          pathCommit_ = java.util.Collections.unmodifiableList(pathCommit_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ToDataNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ToDataNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              undo.proto.FromManagerProto.ToDataNode.class, undo.proto.FromManagerProto.ToDataNode.Builder.class);
    }

    public static com.google.protobuf.Parser<ToDataNode> PARSER =
        new com.google.protobuf.AbstractParser<ToDataNode>() {
      public ToDataNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToDataNode(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ToDataNode> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 newCommit = 1;
    public static final int NEWCOMMIT_FIELD_NUMBER = 1;
    private long newCommit_;
    /**
     * <code>optional int64 newCommit = 1;</code>
     */
    public boolean hasNewCommit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 newCommit = 1;</code>
     */
    public long getNewCommit() {
      return newCommit_;
    }

    // optional bool resetDependencies = 2;
    public static final int RESETDEPENDENCIES_FIELD_NUMBER = 2;
    private boolean resetDependencies_;
    /**
     * <code>optional bool resetDependencies = 2;</code>
     */
    public boolean hasResetDependencies() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool resetDependencies = 2;</code>
     */
    public boolean getResetDependencies() {
      return resetDependencies_;
    }

    // optional bool redoOver = 3;
    public static final int REDOOVER_FIELD_NUMBER = 3;
    private boolean redoOver_;
    /**
     * <code>optional bool redoOver = 3;</code>
     */
    public boolean hasRedoOver() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool redoOver = 3;</code>
     */
    public boolean getRedoOver() {
      return redoOver_;
    }

    // repeated int32 pathBranch = 4;
    public static final int PATHBRANCH_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> pathBranch_;
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getPathBranchList() {
      return pathBranch_;
    }
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    public int getPathBranchCount() {
      return pathBranch_.size();
    }
    /**
     * <code>repeated int32 pathBranch = 4;</code>
     */
    public int getPathBranch(int index) {
      return pathBranch_.get(index);
    }

    // repeated int64 pathCommit = 5;
    public static final int PATHCOMMIT_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> pathCommit_;
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getPathCommitList() {
      return pathCommit_;
    }
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    public int getPathCommitCount() {
      return pathCommit_.size();
    }
    /**
     * <code>repeated int64 pathCommit = 5;</code>
     */
    public long getPathCommit(int index) {
      return pathCommit_.get(index);
    }

    private void initFields() {
      newCommit_ = 0L;
      resetDependencies_ = false;
      redoOver_ = false;
      pathBranch_ = java.util.Collections.emptyList();
      pathCommit_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newCommit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, resetDependencies_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, redoOver_);
      }
      for (int i = 0; i < pathBranch_.size(); i++) {
        output.writeInt32(4, pathBranch_.get(i));
      }
      for (int i = 0; i < pathCommit_.size(); i++) {
        output.writeInt64(5, pathCommit_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newCommit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, resetDependencies_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, redoOver_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pathBranch_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(pathBranch_.get(i));
        }
        size += dataSize;
        size += 1 * getPathBranchList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pathCommit_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(pathCommit_.get(i));
        }
        size += dataSize;
        size += 1 * getPathCommitList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ToDataNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(undo.proto.FromManagerProto.ToDataNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.ToDataNode}
     *
     * <pre>
     *To data node
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements undo.proto.FromManagerProto.ToDataNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ToDataNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ToDataNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                undo.proto.FromManagerProto.ToDataNode.class, undo.proto.FromManagerProto.ToDataNode.Builder.class);
      }

      // Construct using undo.proto.FromManagerProto.ToDataNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newCommit_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        resetDependencies_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        redoOver_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        pathBranch_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        pathCommit_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ToDataNode_descriptor;
      }

      public undo.proto.FromManagerProto.ToDataNode getDefaultInstanceForType() {
        return undo.proto.FromManagerProto.ToDataNode.getDefaultInstance();
      }

      public undo.proto.FromManagerProto.ToDataNode build() {
        undo.proto.FromManagerProto.ToDataNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public undo.proto.FromManagerProto.ToDataNode buildPartial() {
        undo.proto.FromManagerProto.ToDataNode result = new undo.proto.FromManagerProto.ToDataNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newCommit_ = newCommit_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resetDependencies_ = resetDependencies_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.redoOver_ = redoOver_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          pathBranch_ = java.util.Collections.unmodifiableList(pathBranch_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.pathBranch_ = pathBranch_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          pathCommit_ = java.util.Collections.unmodifiableList(pathCommit_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.pathCommit_ = pathCommit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof undo.proto.FromManagerProto.ToDataNode) {
          return mergeFrom((undo.proto.FromManagerProto.ToDataNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(undo.proto.FromManagerProto.ToDataNode other) {
        if (other == undo.proto.FromManagerProto.ToDataNode.getDefaultInstance()) return this;
        if (other.hasNewCommit()) {
          setNewCommit(other.getNewCommit());
        }
        if (other.hasResetDependencies()) {
          setResetDependencies(other.getResetDependencies());
        }
        if (other.hasRedoOver()) {
          setRedoOver(other.getRedoOver());
        }
        if (!other.pathBranch_.isEmpty()) {
          if (pathBranch_.isEmpty()) {
            pathBranch_ = other.pathBranch_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePathBranchIsMutable();
            pathBranch_.addAll(other.pathBranch_);
          }
          onChanged();
        }
        if (!other.pathCommit_.isEmpty()) {
          if (pathCommit_.isEmpty()) {
            pathCommit_ = other.pathCommit_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePathCommitIsMutable();
            pathCommit_.addAll(other.pathCommit_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        undo.proto.FromManagerProto.ToDataNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (undo.proto.FromManagerProto.ToDataNode) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 newCommit = 1;
      private long newCommit_ ;
      /**
       * <code>optional int64 newCommit = 1;</code>
       */
      public boolean hasNewCommit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 newCommit = 1;</code>
       */
      public long getNewCommit() {
        return newCommit_;
      }
      /**
       * <code>optional int64 newCommit = 1;</code>
       */
      public Builder setNewCommit(long value) {
        bitField0_ |= 0x00000001;
        newCommit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 newCommit = 1;</code>
       */
      public Builder clearNewCommit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newCommit_ = 0L;
        onChanged();
        return this;
      }

      // optional bool resetDependencies = 2;
      private boolean resetDependencies_ ;
      /**
       * <code>optional bool resetDependencies = 2;</code>
       */
      public boolean hasResetDependencies() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool resetDependencies = 2;</code>
       */
      public boolean getResetDependencies() {
        return resetDependencies_;
      }
      /**
       * <code>optional bool resetDependencies = 2;</code>
       */
      public Builder setResetDependencies(boolean value) {
        bitField0_ |= 0x00000002;
        resetDependencies_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool resetDependencies = 2;</code>
       */
      public Builder clearResetDependencies() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resetDependencies_ = false;
        onChanged();
        return this;
      }

      // optional bool redoOver = 3;
      private boolean redoOver_ ;
      /**
       * <code>optional bool redoOver = 3;</code>
       */
      public boolean hasRedoOver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool redoOver = 3;</code>
       */
      public boolean getRedoOver() {
        return redoOver_;
      }
      /**
       * <code>optional bool redoOver = 3;</code>
       */
      public Builder setRedoOver(boolean value) {
        bitField0_ |= 0x00000004;
        redoOver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool redoOver = 3;</code>
       */
      public Builder clearRedoOver() {
        bitField0_ = (bitField0_ & ~0x00000004);
        redoOver_ = false;
        onChanged();
        return this;
      }

      // repeated int32 pathBranch = 4;
      private java.util.List<java.lang.Integer> pathBranch_ = java.util.Collections.emptyList();
      private void ensurePathBranchIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          pathBranch_ = new java.util.ArrayList<java.lang.Integer>(pathBranch_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getPathBranchList() {
        return java.util.Collections.unmodifiableList(pathBranch_);
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public int getPathBranchCount() {
        return pathBranch_.size();
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public int getPathBranch(int index) {
        return pathBranch_.get(index);
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public Builder setPathBranch(
          int index, int value) {
        ensurePathBranchIsMutable();
        pathBranch_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public Builder addPathBranch(int value) {
        ensurePathBranchIsMutable();
        pathBranch_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public Builder addAllPathBranch(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePathBranchIsMutable();
        super.addAll(values, pathBranch_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pathBranch = 4;</code>
       */
      public Builder clearPathBranch() {
        pathBranch_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated int64 pathCommit = 5;
      private java.util.List<java.lang.Long> pathCommit_ = java.util.Collections.emptyList();
      private void ensurePathCommitIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          pathCommit_ = new java.util.ArrayList<java.lang.Long>(pathCommit_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getPathCommitList() {
        return java.util.Collections.unmodifiableList(pathCommit_);
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public int getPathCommitCount() {
        return pathCommit_.size();
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public long getPathCommit(int index) {
        return pathCommit_.get(index);
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public Builder setPathCommit(
          int index, long value) {
        ensurePathCommitIsMutable();
        pathCommit_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public Builder addPathCommit(long value) {
        ensurePathCommitIsMutable();
        pathCommit_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public Builder addAllPathCommit(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensurePathCommitIsMutable();
        super.addAll(values, pathCommit_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pathCommit = 5;</code>
       */
      public Builder clearPathCommit() {
        pathCommit_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.ToDataNode)
    }

    static {
      defaultInstance = new ToDataNode(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.ToDataNode)
  }

  public interface ExecListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 rid = 1;
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    java.util.List<java.lang.Long> getRidList();
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    int getRidCount();
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    long getRid(int index);

    // required int32 branch = 2;
    /**
     * <code>required int32 branch = 2;</code>
     */
    boolean hasBranch();
    /**
     * <code>required int32 branch = 2;</code>
     */
    int getBranch();

    // required bool start = 3;
    /**
     * <code>required bool start = 3;</code>
     */
    boolean hasStart();
    /**
     * <code>required bool start = 3;</code>
     */
    boolean getStart();
  }
  /**
   * Protobuf type {@code voldemort.ExecList}
   *
   * <pre>
   *To redo node
   * </pre>
   */
  public static final class ExecList extends
      com.google.protobuf.GeneratedMessage
      implements ExecListOrBuilder {
    // Use ExecList.newBuilder() to construct.
    private ExecList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExecList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExecList defaultInstance;
    public static ExecList getDefaultInstance() {
      return defaultInstance;
    }

    public ExecList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExecList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              rid_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                rid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                rid_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              branch_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              start_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = java.util.Collections.unmodifiableList(rid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ExecList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              undo.proto.FromManagerProto.ExecList.class, undo.proto.FromManagerProto.ExecList.Builder.class);
    }

    public static com.google.protobuf.Parser<ExecList> PARSER =
        new com.google.protobuf.AbstractParser<ExecList>() {
      public ExecList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExecList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> rid_;
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getRidList() {
      return rid_;
    }
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public int getRidCount() {
      return rid_.size();
    }
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public long getRid(int index) {
      return rid_.get(index);
    }

    // required int32 branch = 2;
    public static final int BRANCH_FIELD_NUMBER = 2;
    private int branch_;
    /**
     * <code>required int32 branch = 2;</code>
     */
    public boolean hasBranch() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 branch = 2;</code>
     */
    public int getBranch() {
      return branch_;
    }

    // required bool start = 3;
    public static final int START_FIELD_NUMBER = 3;
    private boolean start_;
    /**
     * <code>required bool start = 3;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool start = 3;</code>
     */
    public boolean getStart() {
      return start_;
    }

    private void initFields() {
      rid_ = java.util.Collections.emptyList();
      branch_ = 0;
      start_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBranch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rid_.size(); i++) {
        output.writeInt64(1, rid_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, branch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, start_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < rid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(rid_.get(i));
        }
        size += dataSize;
        size += 1 * getRidList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, branch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, start_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static undo.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ExecList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static undo.proto.FromManagerProto.ExecList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(undo.proto.FromManagerProto.ExecList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.ExecList}
     *
     * <pre>
     *To redo node
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements undo.proto.FromManagerProto.ExecListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ExecList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                undo.proto.FromManagerProto.ExecList.class, undo.proto.FromManagerProto.ExecList.Builder.class);
      }

      // Construct using undo.proto.FromManagerProto.ExecList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        branch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        start_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
      }

      public undo.proto.FromManagerProto.ExecList getDefaultInstanceForType() {
        return undo.proto.FromManagerProto.ExecList.getDefaultInstance();
      }

      public undo.proto.FromManagerProto.ExecList build() {
        undo.proto.FromManagerProto.ExecList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public undo.proto.FromManagerProto.ExecList buildPartial() {
        undo.proto.FromManagerProto.ExecList result = new undo.proto.FromManagerProto.ExecList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = java.util.Collections.unmodifiableList(rid_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.branch_ = branch_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.start_ = start_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof undo.proto.FromManagerProto.ExecList) {
          return mergeFrom((undo.proto.FromManagerProto.ExecList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(undo.proto.FromManagerProto.ExecList other) {
        if (other == undo.proto.FromManagerProto.ExecList.getDefaultInstance()) return this;
        if (!other.rid_.isEmpty()) {
          if (rid_.isEmpty()) {
            rid_ = other.rid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRidIsMutable();
            rid_.addAll(other.rid_);
          }
          onChanged();
        }
        if (other.hasBranch()) {
          setBranch(other.getBranch());
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBranch()) {
          
          return false;
        }
        if (!hasStart()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        undo.proto.FromManagerProto.ExecList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (undo.proto.FromManagerProto.ExecList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 rid = 1;
      private java.util.List<java.lang.Long> rid_ = java.util.Collections.emptyList();
      private void ensureRidIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = new java.util.ArrayList<java.lang.Long>(rid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getRidList() {
        return java.util.Collections.unmodifiableList(rid_);
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public int getRidCount() {
        return rid_.size();
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public long getRid(int index) {
        return rid_.get(index);
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder setRid(
          int index, long value) {
        ensureRidIsMutable();
        rid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder addRid(long value) {
        ensureRidIsMutable();
        rid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder addAllRid(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureRidIsMutable();
        super.addAll(values, rid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder clearRid() {
        rid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // required int32 branch = 2;
      private int branch_ ;
      /**
       * <code>required int32 branch = 2;</code>
       */
      public boolean hasBranch() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 branch = 2;</code>
       */
      public int getBranch() {
        return branch_;
      }
      /**
       * <code>required int32 branch = 2;</code>
       */
      public Builder setBranch(int value) {
        bitField0_ |= 0x00000002;
        branch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 branch = 2;</code>
       */
      public Builder clearBranch() {
        bitField0_ = (bitField0_ & ~0x00000002);
        branch_ = 0;
        onChanged();
        return this;
      }

      // required bool start = 3;
      private boolean start_ ;
      /**
       * <code>required bool start = 3;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool start = 3;</code>
       */
      public boolean getStart() {
        return start_;
      }
      /**
       * <code>required bool start = 3;</code>
       */
      public Builder setStart(boolean value) {
        bitField0_ |= 0x00000004;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool start = 3;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.ExecList)
    }

    static {
      defaultInstance = new ExecList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.ExecList)
  }

  public interface ProxyMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 branch = 1;
    /**
     * <code>optional int32 branch = 1;</code>
     */
    boolean hasBranch();
    /**
     * <code>optional int32 branch = 1;</code>
     */
    int getBranch();

    // optional bool restrain = 2;
    /**
     * <code>optional bool restrain = 2;</code>
     */
    boolean hasRestrain();
    /**
     * <code>optional bool restrain = 2;</code>
     */
    boolean getRestrain();

    // optional int64 timeTravel = 3;
    /**
     * <code>optional int64 timeTravel = 3;</code>
     */
    boolean hasTimeTravel();
    /**
     * <code>optional int64 timeTravel = 3;</code>
     */
    long getTimeTravel();
  }
  /**
   * Protobuf type {@code voldemort.ProxyMsg}
   *
   * <pre>
   *To proxy
   * </pre>
   */
  public static final class ProxyMsg extends
      com.google.protobuf.GeneratedMessage
      implements ProxyMsgOrBuilder {
    // Use ProxyMsg.newBuilder() to construct.
    private ProxyMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProxyMsg defaultInstance;
    public static ProxyMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProxyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              branch_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              restrain_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeTravel_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ProxyMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return undo.proto.FromManagerProto.internal_static_voldemort_ProxyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              undo.proto.FromManagerProto.ProxyMsg.class, undo.proto.FromManagerProto.ProxyMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ProxyMsg> PARSER =
        new com.google.protobuf.AbstractParser<ProxyMsg>() {
      public ProxyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProxyMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 branch = 1;
    public static final int BRANCH_FIELD_NUMBER = 1;
    private int branch_;
    /**
     * <code>optional int32 branch = 1;</code>
     */
    public boolean hasBranch() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 branch = 1;</code>
     */
    public int getBranch() {
      return branch_;
    }

    // optional bool restrain = 2;
    public static final int RESTRAIN_FIELD_NUMBER = 2;
    private boolean restrain_;
    /**
     * <code>optional bool restrain = 2;</code>
     */
    public boolean hasRestrain() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool restrain = 2;</code>
     */
    public boolean getRestrain() {
      return restrain_;
    }

    // optional int64 timeTravel = 3;
    public static final int TIMETRAVEL_FIELD_NUMBER = 3;
    private long timeTravel_;
    /**
     * <code>optional int64 timeTravel = 3;</code>
     */
    public boolean hasTimeTravel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timeTravel = 3;</code>
     */
    public long getTimeTravel() {
      return timeTravel_;
    }

    private void initFields() {
      branch_ = 0;
      restrain_ = false;
      timeTravel_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, branch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, restrain_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeTravel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, branch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, restrain_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeTravel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static undo.proto.FromManagerProto.ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(undo.proto.FromManagerProto.ProxyMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.ProxyMsg}
     *
     * <pre>
     *To proxy
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements undo.proto.FromManagerProto.ProxyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ProxyMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ProxyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                undo.proto.FromManagerProto.ProxyMsg.class, undo.proto.FromManagerProto.ProxyMsg.Builder.class);
      }

      // Construct using undo.proto.FromManagerProto.ProxyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        branch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        restrain_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeTravel_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return undo.proto.FromManagerProto.internal_static_voldemort_ProxyMsg_descriptor;
      }

      public undo.proto.FromManagerProto.ProxyMsg getDefaultInstanceForType() {
        return undo.proto.FromManagerProto.ProxyMsg.getDefaultInstance();
      }

      public undo.proto.FromManagerProto.ProxyMsg build() {
        undo.proto.FromManagerProto.ProxyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public undo.proto.FromManagerProto.ProxyMsg buildPartial() {
        undo.proto.FromManagerProto.ProxyMsg result = new undo.proto.FromManagerProto.ProxyMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.branch_ = branch_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.restrain_ = restrain_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeTravel_ = timeTravel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof undo.proto.FromManagerProto.ProxyMsg) {
          return mergeFrom((undo.proto.FromManagerProto.ProxyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(undo.proto.FromManagerProto.ProxyMsg other) {
        if (other == undo.proto.FromManagerProto.ProxyMsg.getDefaultInstance()) return this;
        if (other.hasBranch()) {
          setBranch(other.getBranch());
        }
        if (other.hasRestrain()) {
          setRestrain(other.getRestrain());
        }
        if (other.hasTimeTravel()) {
          setTimeTravel(other.getTimeTravel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        undo.proto.FromManagerProto.ProxyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (undo.proto.FromManagerProto.ProxyMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 branch = 1;
      private int branch_ ;
      /**
       * <code>optional int32 branch = 1;</code>
       */
      public boolean hasBranch() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 branch = 1;</code>
       */
      public int getBranch() {
        return branch_;
      }
      /**
       * <code>optional int32 branch = 1;</code>
       */
      public Builder setBranch(int value) {
        bitField0_ |= 0x00000001;
        branch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 branch = 1;</code>
       */
      public Builder clearBranch() {
        bitField0_ = (bitField0_ & ~0x00000001);
        branch_ = 0;
        onChanged();
        return this;
      }

      // optional bool restrain = 2;
      private boolean restrain_ ;
      /**
       * <code>optional bool restrain = 2;</code>
       */
      public boolean hasRestrain() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool restrain = 2;</code>
       */
      public boolean getRestrain() {
        return restrain_;
      }
      /**
       * <code>optional bool restrain = 2;</code>
       */
      public Builder setRestrain(boolean value) {
        bitField0_ |= 0x00000002;
        restrain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool restrain = 2;</code>
       */
      public Builder clearRestrain() {
        bitField0_ = (bitField0_ & ~0x00000002);
        restrain_ = false;
        onChanged();
        return this;
      }

      // optional int64 timeTravel = 3;
      private long timeTravel_ ;
      /**
       * <code>optional int64 timeTravel = 3;</code>
       */
      public boolean hasTimeTravel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timeTravel = 3;</code>
       */
      public long getTimeTravel() {
        return timeTravel_;
      }
      /**
       * <code>optional int64 timeTravel = 3;</code>
       */
      public Builder setTimeTravel(long value) {
        bitField0_ |= 0x00000004;
        timeTravel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timeTravel = 3;</code>
       */
      public Builder clearTimeTravel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeTravel_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.ProxyMsg)
    }

    static {
      defaultInstance = new ProxyMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.ProxyMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_ToDataNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_ToDataNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_ExecList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_ExecList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_ProxyMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_ProxyMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022from-manager.proto\022\tvoldemort\"t\n\nToDat" +
      "aNode\022\021\n\tnewCommit\030\001 \001(\003\022\031\n\021resetDepende" +
      "ncies\030\002 \001(\010\022\020\n\010redoOver\030\003 \001(\010\022\022\n\npathBra" +
      "nch\030\004 \003(\005\022\022\n\npathCommit\030\005 \003(\003\"6\n\010ExecLis" +
      "t\022\013\n\003rid\030\001 \003(\003\022\016\n\006branch\030\002 \002(\005\022\r\n\005start\030" +
      "\003 \002(\010\"@\n\010ProxyMsg\022\016\n\006branch\030\001 \001(\005\022\020\n\010res" +
      "train\030\002 \001(\010\022\022\n\ntimeTravel\030\003 \001(\003B \n\nundo." +
      "protoB\020FromManagerProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_voldemort_ToDataNode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_voldemort_ToDataNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_ToDataNode_descriptor,
              new java.lang.String[] { "NewCommit", "ResetDependencies", "RedoOver", "PathBranch", "PathCommit", });
          internal_static_voldemort_ExecList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_voldemort_ExecList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_ExecList_descriptor,
              new java.lang.String[] { "Rid", "Branch", "Start", });
          internal_static_voldemort_ProxyMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_voldemort_ProxyMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_ProxyMsg_descriptor,
              new java.lang.String[] { "Branch", "Restrain", "TimeTravel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
