// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: from-manager.proto

package voldemort.undoTracker.proto;

public final class FromManagerProto {
  private FromManagerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SnapshotOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 seasonId = 1;
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    boolean hasSeasonId();
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    long getSeasonId();
  }
  /**
   * Protobuf type {@code voldemort.Snapshot}
   *
   * <pre>
   *To data node
   * </pre>
   */
  public static final class Snapshot extends
      com.google.protobuf.GeneratedMessage
      implements SnapshotOrBuilder {
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Snapshot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Snapshot defaultInstance;
    public static Snapshot getDefaultInstance() {
      return defaultInstance;
    }

    public Snapshot getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seasonId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_Snapshot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              voldemort.undoTracker.proto.FromManagerProto.Snapshot.class, voldemort.undoTracker.proto.FromManagerProto.Snapshot.Builder.class);
    }

    public static com.google.protobuf.Parser<Snapshot> PARSER =
        new com.google.protobuf.AbstractParser<Snapshot>() {
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshot(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 seasonId = 1;
    public static final int SEASONID_FIELD_NUMBER = 1;
    private long seasonId_;
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    public boolean hasSeasonId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    public long getSeasonId() {
      return seasonId_;
    }

    private void initFields() {
      seasonId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSeasonId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seasonId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seasonId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(voldemort.undoTracker.proto.FromManagerProto.Snapshot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.Snapshot}
     *
     * <pre>
     *To data node
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements voldemort.undoTracker.proto.FromManagerProto.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_Snapshot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                voldemort.undoTracker.proto.FromManagerProto.Snapshot.class, voldemort.undoTracker.proto.FromManagerProto.Snapshot.Builder.class);
      }

      // Construct using voldemort.undoTracker.proto.FromManagerProto.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        seasonId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_Snapshot_descriptor;
      }

      public voldemort.undoTracker.proto.FromManagerProto.Snapshot getDefaultInstanceForType() {
        return voldemort.undoTracker.proto.FromManagerProto.Snapshot.getDefaultInstance();
      }

      public voldemort.undoTracker.proto.FromManagerProto.Snapshot build() {
        voldemort.undoTracker.proto.FromManagerProto.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public voldemort.undoTracker.proto.FromManagerProto.Snapshot buildPartial() {
        voldemort.undoTracker.proto.FromManagerProto.Snapshot result = new voldemort.undoTracker.proto.FromManagerProto.Snapshot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seasonId_ = seasonId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof voldemort.undoTracker.proto.FromManagerProto.Snapshot) {
          return mergeFrom((voldemort.undoTracker.proto.FromManagerProto.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(voldemort.undoTracker.proto.FromManagerProto.Snapshot other) {
        if (other == voldemort.undoTracker.proto.FromManagerProto.Snapshot.getDefaultInstance()) return this;
        if (other.hasSeasonId()) {
          setSeasonId(other.getSeasonId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSeasonId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        voldemort.undoTracker.proto.FromManagerProto.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (voldemort.undoTracker.proto.FromManagerProto.Snapshot) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 seasonId = 1;
      private long seasonId_ ;
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public boolean hasSeasonId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public long getSeasonId() {
        return seasonId_;
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public Builder setSeasonId(long value) {
        bitField0_ |= 0x00000001;
        seasonId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public Builder clearSeasonId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seasonId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.Snapshot)
    }

    static {
      defaultInstance = new Snapshot(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.Snapshot)
  }

  public interface ExecListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 rid = 1;
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    java.util.List<java.lang.Long> getRidList();
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    int getRidCount();
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    long getRid(int index);
  }
  /**
   * Protobuf type {@code voldemort.ExecList}
   *
   * <pre>
   *To redo node
   * </pre>
   */
  public static final class ExecList extends
      com.google.protobuf.GeneratedMessage
      implements ExecListOrBuilder {
    // Use ExecList.newBuilder() to construct.
    private ExecList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExecList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExecList defaultInstance;
    public static ExecList getDefaultInstance() {
      return defaultInstance;
    }

    public ExecList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExecList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              rid_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                rid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                rid_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = java.util.Collections.unmodifiableList(rid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_ExecList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              voldemort.undoTracker.proto.FromManagerProto.ExecList.class, voldemort.undoTracker.proto.FromManagerProto.ExecList.Builder.class);
    }

    public static com.google.protobuf.Parser<ExecList> PARSER =
        new com.google.protobuf.AbstractParser<ExecList>() {
      public ExecList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExecList> getParserForType() {
      return PARSER;
    }

    // repeated int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> rid_;
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getRidList() {
      return rid_;
    }
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public int getRidCount() {
      return rid_.size();
    }
    /**
     * <code>repeated int64 rid = 1;</code>
     */
    public long getRid(int index) {
      return rid_.get(index);
    }

    private void initFields() {
      rid_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rid_.size(); i++) {
        output.writeInt64(1, rid_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < rid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(rid_.get(i));
        }
        size += dataSize;
        size += 1 * getRidList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.FromManagerProto.ExecList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(voldemort.undoTracker.proto.FromManagerProto.ExecList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.ExecList}
     *
     * <pre>
     *To redo node
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements voldemort.undoTracker.proto.FromManagerProto.ExecListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_ExecList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                voldemort.undoTracker.proto.FromManagerProto.ExecList.class, voldemort.undoTracker.proto.FromManagerProto.ExecList.Builder.class);
      }

      // Construct using voldemort.undoTracker.proto.FromManagerProto.ExecList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return voldemort.undoTracker.proto.FromManagerProto.internal_static_voldemort_ExecList_descriptor;
      }

      public voldemort.undoTracker.proto.FromManagerProto.ExecList getDefaultInstanceForType() {
        return voldemort.undoTracker.proto.FromManagerProto.ExecList.getDefaultInstance();
      }

      public voldemort.undoTracker.proto.FromManagerProto.ExecList build() {
        voldemort.undoTracker.proto.FromManagerProto.ExecList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public voldemort.undoTracker.proto.FromManagerProto.ExecList buildPartial() {
        voldemort.undoTracker.proto.FromManagerProto.ExecList result = new voldemort.undoTracker.proto.FromManagerProto.ExecList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = java.util.Collections.unmodifiableList(rid_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rid_ = rid_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof voldemort.undoTracker.proto.FromManagerProto.ExecList) {
          return mergeFrom((voldemort.undoTracker.proto.FromManagerProto.ExecList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(voldemort.undoTracker.proto.FromManagerProto.ExecList other) {
        if (other == voldemort.undoTracker.proto.FromManagerProto.ExecList.getDefaultInstance()) return this;
        if (!other.rid_.isEmpty()) {
          if (rid_.isEmpty()) {
            rid_ = other.rid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRidIsMutable();
            rid_.addAll(other.rid_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        voldemort.undoTracker.proto.FromManagerProto.ExecList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (voldemort.undoTracker.proto.FromManagerProto.ExecList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 rid = 1;
      private java.util.List<java.lang.Long> rid_ = java.util.Collections.emptyList();
      private void ensureRidIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rid_ = new java.util.ArrayList<java.lang.Long>(rid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getRidList() {
        return java.util.Collections.unmodifiableList(rid_);
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public int getRidCount() {
        return rid_.size();
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public long getRid(int index) {
        return rid_.get(index);
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder setRid(
          int index, long value) {
        ensureRidIsMutable();
        rid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder addRid(long value) {
        ensureRidIsMutable();
        rid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder addAllRid(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureRidIsMutable();
        super.addAll(values, rid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 rid = 1;</code>
       */
      public Builder clearRid() {
        rid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.ExecList)
    }

    static {
      defaultInstance = new ExecList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.ExecList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_Snapshot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_Snapshot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_ExecList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_ExecList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022from-manager.proto\022\tvoldemort\"\034\n\010Snaps" +
      "hot\022\020\n\010seasonId\030\001 \002(\003\"\027\n\010ExecList\022\013\n\003rid" +
      "\030\001 \003(\003B1\n\033voldemort.undoTracker.protoB\020F" +
      "romManagerProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_voldemort_Snapshot_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_voldemort_Snapshot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_Snapshot_descriptor,
              new java.lang.String[] { "SeasonId", });
          internal_static_voldemort_ExecList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_voldemort_ExecList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_ExecList_descriptor,
              new java.lang.String[] { "Rid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
