// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbNode-undo.proto

package voldemort.undoTracker.proto;

public final class OpProto {
  private OpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TrackEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rid = 1;
    /**
     * <code>required int64 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int64 rid = 1;</code>
     */
    long getRid();

    // repeated int64 dependencies = 2;
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    java.util.List<java.lang.Long> getDependenciesList();
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    int getDependenciesCount();
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    long getDependencies(int index);
  }
  /**
   * Protobuf type {@code voldemort.TrackEntry}
   */
  public static final class TrackEntry extends
      com.google.protobuf.GeneratedMessage
      implements TrackEntryOrBuilder {
    // Use TrackEntry.newBuilder() to construct.
    private TrackEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TrackEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TrackEntry defaultInstance;
    public static TrackEntry getDefaultInstance() {
      return defaultInstance;
    }

    public TrackEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TrackEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dependencies_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              dependencies_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                dependencies_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                dependencies_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              voldemort.undoTracker.proto.OpProto.TrackEntry.class, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<TrackEntry> PARSER =
        new com.google.protobuf.AbstractParser<TrackEntry>() {
      public TrackEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrackEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrackEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    /**
     * <code>required int64 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rid = 1;</code>
     */
    public long getRid() {
      return rid_;
    }

    // repeated int64 dependencies = 2;
    public static final int DEPENDENCIES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> dependencies_;
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getDependenciesList() {
      return dependencies_;
    }
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    /**
     * <code>repeated int64 dependencies = 2;</code>
     */
    public long getDependencies(int index) {
      return dependencies_.get(index);
    }

    private void initFields() {
      rid_ = 0L;
      dependencies_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rid_);
      }
      for (int i = 0; i < dependencies_.size(); i++) {
        output.writeInt64(2, dependencies_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dependencies_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(dependencies_.get(i));
        }
        size += dataSize;
        size += 1 * getDependenciesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(voldemort.undoTracker.proto.OpProto.TrackEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.TrackEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                voldemort.undoTracker.proto.OpProto.TrackEntry.class, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder.class);
      }

      // Construct using voldemort.undoTracker.proto.OpProto.TrackEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        dependencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackEntry_descriptor;
      }

      public voldemort.undoTracker.proto.OpProto.TrackEntry getDefaultInstanceForType() {
        return voldemort.undoTracker.proto.OpProto.TrackEntry.getDefaultInstance();
      }

      public voldemort.undoTracker.proto.OpProto.TrackEntry build() {
        voldemort.undoTracker.proto.OpProto.TrackEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public voldemort.undoTracker.proto.OpProto.TrackEntry buildPartial() {
        voldemort.undoTracker.proto.OpProto.TrackEntry result = new voldemort.undoTracker.proto.OpProto.TrackEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dependencies_ = dependencies_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof voldemort.undoTracker.proto.OpProto.TrackEntry) {
          return mergeFrom((voldemort.undoTracker.proto.OpProto.TrackEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(voldemort.undoTracker.proto.OpProto.TrackEntry other) {
        if (other == voldemort.undoTracker.proto.OpProto.TrackEntry.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (!other.dependencies_.isEmpty()) {
          if (dependencies_.isEmpty()) {
            dependencies_ = other.dependencies_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDependenciesIsMutable();
            dependencies_.addAll(other.dependencies_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        voldemort.undoTracker.proto.OpProto.TrackEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (voldemort.undoTracker.proto.OpProto.TrackEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rid = 1;
      private long rid_ ;
      /**
       * <code>required int64 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 dependencies = 2;
      private java.util.List<java.lang.Long> dependencies_ = java.util.Collections.emptyList();
      private void ensureDependenciesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dependencies_ = new java.util.ArrayList<java.lang.Long>(dependencies_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getDependenciesList() {
        return java.util.Collections.unmodifiableList(dependencies_);
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public int getDependenciesCount() {
        return dependencies_.size();
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public long getDependencies(int index) {
        return dependencies_.get(index);
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public Builder setDependencies(
          int index, long value) {
        ensureDependenciesIsMutable();
        dependencies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public Builder addDependencies(long value) {
        ensureDependenciesIsMutable();
        dependencies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public Builder addAllDependencies(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDependenciesIsMutable();
        super.addAll(values, dependencies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dependencies = 2;</code>
       */
      public Builder clearDependencies() {
        dependencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.TrackEntry)
    }

    static {
      defaultInstance = new TrackEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.TrackEntry)
  }

  public interface TrackListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .voldemort.TrackEntry entry = 1;
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry> 
        getEntryList();
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    voldemort.undoTracker.proto.OpProto.TrackEntry getEntry(int index);
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    java.util.List<? extends voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder> 
        getEntryOrBuilderList();
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder getEntryOrBuilder(
        int index);

    // optional string nodeId = 2;
    /**
     * <code>optional string nodeId = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();
  }
  /**
   * Protobuf type {@code voldemort.TrackList}
   */
  public static final class TrackList extends
      com.google.protobuf.GeneratedMessage
      implements TrackListOrBuilder {
    // Use TrackList.newBuilder() to construct.
    private TrackList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TrackList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TrackList defaultInstance;
    public static TrackList getDefaultInstance() {
      return defaultInstance;
    }

    public TrackList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TrackList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new java.util.ArrayList<voldemort.undoTracker.proto.OpProto.TrackEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(input.readMessage(voldemort.undoTracker.proto.OpProto.TrackEntry.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              voldemort.undoTracker.proto.OpProto.TrackList.class, voldemort.undoTracker.proto.OpProto.TrackList.Builder.class);
    }

    public static com.google.protobuf.Parser<TrackList> PARSER =
        new com.google.protobuf.AbstractParser<TrackList>() {
      public TrackList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrackList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrackList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .voldemort.TrackEntry entry = 1;
    public static final int ENTRY_FIELD_NUMBER = 1;
    private java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry> entry_;
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    public java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    public java.util.List<? extends voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    public voldemort.undoTracker.proto.OpProto.TrackEntry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .voldemort.TrackEntry entry = 1;</code>
     */
    public voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    // optional string nodeId = 2;
    public static final int NODEID_FIELD_NUMBER = 2;
    private java.lang.Object nodeId_;
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      entry_ = java.util.Collections.emptyList();
      nodeId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getNodeIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNodeIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.TrackList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(voldemort.undoTracker.proto.OpProto.TrackList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.TrackList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements voldemort.undoTracker.proto.OpProto.TrackListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                voldemort.undoTracker.proto.OpProto.TrackList.class, voldemort.undoTracker.proto.OpProto.TrackList.Builder.class);
      }

      // Construct using voldemort.undoTracker.proto.OpProto.TrackList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entryBuilder_.clear();
        }
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_TrackList_descriptor;
      }

      public voldemort.undoTracker.proto.OpProto.TrackList getDefaultInstanceForType() {
        return voldemort.undoTracker.proto.OpProto.TrackList.getDefaultInstance();
      }

      public voldemort.undoTracker.proto.OpProto.TrackList build() {
        voldemort.undoTracker.proto.OpProto.TrackList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public voldemort.undoTracker.proto.OpProto.TrackList buildPartial() {
        voldemort.undoTracker.proto.OpProto.TrackList result = new voldemort.undoTracker.proto.OpProto.TrackList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof voldemort.undoTracker.proto.OpProto.TrackList) {
          return mergeFrom((voldemort.undoTracker.proto.OpProto.TrackList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(voldemort.undoTracker.proto.OpProto.TrackList other) {
        if (other == voldemort.undoTracker.proto.OpProto.TrackList.getDefaultInstance()) return this;
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        if (other.hasNodeId()) {
          bitField0_ |= 0x00000002;
          nodeId_ = other.nodeId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        voldemort.undoTracker.proto.OpProto.TrackList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (voldemort.undoTracker.proto.OpProto.TrackList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .voldemort.TrackEntry entry = 1;
      private java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new java.util.ArrayList<voldemort.undoTracker.proto.OpProto.TrackEntry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          voldemort.undoTracker.proto.OpProto.TrackEntry, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder, voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public voldemort.undoTracker.proto.OpProto.TrackEntry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, voldemort.undoTracker.proto.OpProto.TrackEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder addEntry(voldemort.undoTracker.proto.OpProto.TrackEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, voldemort.undoTracker.proto.OpProto.TrackEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder addEntry(
          voldemort.undoTracker.proto.OpProto.TrackEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder addAllEntry(
          java.lang.Iterable<? extends voldemort.undoTracker.proto.OpProto.TrackEntry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          super.addAll(values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public voldemort.undoTracker.proto.OpProto.TrackEntry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public java.util.List<? extends voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public voldemort.undoTracker.proto.OpProto.TrackEntry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            voldemort.undoTracker.proto.OpProto.TrackEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public voldemort.undoTracker.proto.OpProto.TrackEntry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, voldemort.undoTracker.proto.OpProto.TrackEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .voldemort.TrackEntry entry = 1;</code>
       */
      public java.util.List<voldemort.undoTracker.proto.OpProto.TrackEntry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          voldemort.undoTracker.proto.OpProto.TrackEntry, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder, voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              voldemort.undoTracker.proto.OpProto.TrackEntry, voldemort.undoTracker.proto.OpProto.TrackEntry.Builder, voldemort.undoTracker.proto.OpProto.TrackEntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // optional string nodeId = 2;
      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.TrackList)
    }

    static {
      defaultInstance = new TrackList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.TrackList)
  }

  public interface SnapshotOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 seasonId = 1;
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    boolean hasSeasonId();
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    long getSeasonId();
  }
  /**
   * Protobuf type {@code voldemort.Snapshot}
   */
  public static final class Snapshot extends
      com.google.protobuf.GeneratedMessage
      implements SnapshotOrBuilder {
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Snapshot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Snapshot defaultInstance;
    public static Snapshot getDefaultInstance() {
      return defaultInstance;
    }

    public Snapshot getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seasonId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_Snapshot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              voldemort.undoTracker.proto.OpProto.Snapshot.class, voldemort.undoTracker.proto.OpProto.Snapshot.Builder.class);
    }

    public static com.google.protobuf.Parser<Snapshot> PARSER =
        new com.google.protobuf.AbstractParser<Snapshot>() {
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshot(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 seasonId = 1;
    public static final int SEASONID_FIELD_NUMBER = 1;
    private long seasonId_;
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    public boolean hasSeasonId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 seasonId = 1;</code>
     */
    public long getSeasonId() {
      return seasonId_;
    }

    private void initFields() {
      seasonId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSeasonId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seasonId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seasonId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static voldemort.undoTracker.proto.OpProto.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(voldemort.undoTracker.proto.OpProto.Snapshot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voldemort.Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements voldemort.undoTracker.proto.OpProto.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_Snapshot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                voldemort.undoTracker.proto.OpProto.Snapshot.class, voldemort.undoTracker.proto.OpProto.Snapshot.Builder.class);
      }

      // Construct using voldemort.undoTracker.proto.OpProto.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        seasonId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return voldemort.undoTracker.proto.OpProto.internal_static_voldemort_Snapshot_descriptor;
      }

      public voldemort.undoTracker.proto.OpProto.Snapshot getDefaultInstanceForType() {
        return voldemort.undoTracker.proto.OpProto.Snapshot.getDefaultInstance();
      }

      public voldemort.undoTracker.proto.OpProto.Snapshot build() {
        voldemort.undoTracker.proto.OpProto.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public voldemort.undoTracker.proto.OpProto.Snapshot buildPartial() {
        voldemort.undoTracker.proto.OpProto.Snapshot result = new voldemort.undoTracker.proto.OpProto.Snapshot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seasonId_ = seasonId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof voldemort.undoTracker.proto.OpProto.Snapshot) {
          return mergeFrom((voldemort.undoTracker.proto.OpProto.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(voldemort.undoTracker.proto.OpProto.Snapshot other) {
        if (other == voldemort.undoTracker.proto.OpProto.Snapshot.getDefaultInstance()) return this;
        if (other.hasSeasonId()) {
          setSeasonId(other.getSeasonId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSeasonId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        voldemort.undoTracker.proto.OpProto.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (voldemort.undoTracker.proto.OpProto.Snapshot) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 seasonId = 1;
      private long seasonId_ ;
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public boolean hasSeasonId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public long getSeasonId() {
        return seasonId_;
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public Builder setSeasonId(long value) {
        bitField0_ |= 0x00000001;
        seasonId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 seasonId = 1;</code>
       */
      public Builder clearSeasonId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seasonId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:voldemort.Snapshot)
    }

    static {
      defaultInstance = new Snapshot(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:voldemort.Snapshot)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_TrackEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_TrackEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_TrackList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_TrackList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_voldemort_Snapshot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_voldemort_Snapshot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021dbNode-undo.proto\022\tvoldemort\"/\n\nTrackE" +
      "ntry\022\013\n\003rid\030\001 \002(\003\022\024\n\014dependencies\030\002 \003(\003\"" +
      "A\n\tTrackList\022$\n\005entry\030\001 \003(\0132\025.voldemort." +
      "TrackEntry\022\016\n\006nodeId\030\002 \001(\t\"\034\n\010Snapshot\022\020" +
      "\n\010seasonId\030\001 \002(\003B(\n\033voldemort.undoTracke" +
      "r.protoB\007OpProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_voldemort_TrackEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_voldemort_TrackEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_TrackEntry_descriptor,
              new java.lang.String[] { "Rid", "Dependencies", });
          internal_static_voldemort_TrackList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_voldemort_TrackList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_TrackList_descriptor,
              new java.lang.String[] { "Entry", "NodeId", });
          internal_static_voldemort_Snapshot_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_voldemort_Snapshot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_voldemort_Snapshot_descriptor,
              new java.lang.String[] { "SeasonId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
