# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AskProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AskProto.proto',
  package='pt.inesc.ask.proto',
  serialized_pb='\n\x0e\x41skProto.proto\x12\x12pt.inesc.ask.proto\"Z\n\x08Question\x12\r\n\x05title\x18\x01 \x02(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x11\n\tanswerIds\x18\x03 \x03(\t\x12\r\n\x05views\x18\x04 \x02(\t\x12\x0f\n\x07\x61nswers\x18\x05 \x02(\t\"]\n\x06\x41nswer\x12\x0e\n\x06\x61uthor\x18\x01 \x02(\t\x12\x0c\n\x04text\x18\x02 \x02(\t\x12\x12\n\nisQuestion\x18\x03 \x02(\x08\x12\r\n\x05votes\x18\x04 \x02(\x05\x12\x12\n\ncommentIds\x18\x05 \x03(\t\"\'\n\x07\x43omment\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x02(\t\"\x16\n\x05Index\x12\r\n\x05\x65ntry\x18\x01 \x03(\t\",\n\x0eStringMapEntry\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x03(\tB\x16\n\x12pt.inesc.ask.protoH\x01')




_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='pt.inesc.ask.proto.Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='pt.inesc.ask.proto.Question.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='pt.inesc.ask.proto.Question.tags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answerIds', full_name='pt.inesc.ask.proto.Question.answerIds', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='views', full_name='pt.inesc.ask.proto.Question.views', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answers', full_name='pt.inesc.ask.proto.Question.answers', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=128,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='pt.inesc.ask.proto.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='pt.inesc.ask.proto.Answer.author', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='pt.inesc.ask.proto.Answer.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isQuestion', full_name='pt.inesc.ask.proto.Answer.isQuestion', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='votes', full_name='pt.inesc.ask.proto.Answer.votes', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commentIds', full_name='pt.inesc.ask.proto.Answer.commentIds', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=223,
)


_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='pt.inesc.ask.proto.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pt.inesc.ask.proto.Comment.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='pt.inesc.ask.proto.Comment.author', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=264,
)


_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='pt.inesc.ask.proto.Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='pt.inesc.ask.proto.Index.entry', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=266,
  serialized_end=288,
)


_STRINGMAPENTRY = _descriptor.Descriptor(
  name='StringMapEntry',
  full_name='pt.inesc.ask.proto.StringMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pt.inesc.ask.proto.StringMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='pt.inesc.ask.proto.StringMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=334,
)

DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
DESCRIPTOR.message_types_by_name['Comment'] = _COMMENT
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
DESCRIPTOR.message_types_by_name['StringMapEntry'] = _STRINGMAPENTRY

class Question(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUESTION

  # @@protoc_insertion_point(class_scope:pt.inesc.ask.proto.Question)

class Answer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANSWER

  # @@protoc_insertion_point(class_scope:pt.inesc.ask.proto.Answer)

class Comment(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMENT

  # @@protoc_insertion_point(class_scope:pt.inesc.ask.proto.Comment)

class Index(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INDEX

  # @@protoc_insertion_point(class_scope:pt.inesc.ask.proto.Index)

class StringMapEntry(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGMAPENTRY

  # @@protoc_insertion_point(class_scope:pt.inesc.ask.proto.StringMapEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\022pt.inesc.ask.protoH\001')
# @@protoc_insertion_point(module_scope)
