# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbNode-undo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dbNode-undo.proto',
  package='voldemort',
  serialized_pb='\n\x11\x64\x62Node-undo.proto\x12\tvoldemort\"/\n\nTrackEntry\x12\x0b\n\x03rid\x18\x01 \x02(\x03\x12\x14\n\x0c\x64\x65pendencies\x18\x02 \x03(\x03\"A\n\tTrackList\x12$\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x15.voldemort.TrackEntry\x12\x0e\n\x06nodeId\x18\x02 \x01(\t\"\x1c\n\x08Snapshot\x12\x10\n\x08seasonId\x18\x01 \x02(\x03\x42(\n\x1bvoldemort.undoTracker.protoB\x07OpProtoH\x01')




_TRACKENTRY = _descriptor.Descriptor(
  name='TrackEntry',
  full_name='voldemort.TrackEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.TrackEntry.rid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='voldemort.TrackEntry.dependencies', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=79,
)


_TRACKLIST = _descriptor.Descriptor(
  name='TrackList',
  full_name='voldemort.TrackList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='voldemort.TrackList.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='voldemort.TrackList.nodeId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=146,
)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='voldemort.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seasonId', full_name='voldemort.Snapshot.seasonId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=148,
  serialized_end=176,
)

_TRACKLIST.fields_by_name['entry'].message_type = _TRACKENTRY
DESCRIPTOR.message_types_by_name['TrackEntry'] = _TRACKENTRY
DESCRIPTOR.message_types_by_name['TrackList'] = _TRACKLIST
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT

class TrackEntry(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKENTRY

  # @@protoc_insertion_point(class_scope:voldemort.TrackEntry)

class TrackList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKLIST

  # @@protoc_insertion_point(class_scope:voldemort.TrackList)

class Snapshot(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SNAPSHOT

  # @@protoc_insertion_point(class_scope:voldemort.Snapshot)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\033voldemort.undoTracker.protoB\007OpProtoH\001')
# @@protoc_insertion_point(module_scope)
