# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: from-manager.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='from-manager.proto',
  package='voldemort',
  serialized_pb='\n\x12\x66rom-manager.proto\x12\tvoldemort\"\xfc\x01\n\nToDataNode\x12\x11\n\tnewCommit\x18\x01 \x01(\x03\x12\x19\n\x11resetDependencies\x18\x02 \x01(\x08\x12\x10\n\x08redoOver\x18\x03 \x01(\x08\x12\x12\n\npathBranch\x18\x04 \x03(\x05\x12\x12\n\npathCommit\x18\x05 \x03(\x03\x12@\n\x10\x65ntryAccessesMsg\x18\x06 \x01(\x0b\x32&.voldemort.ToDataNode.EntryAccessesMsg\x12\x11\n\tshowStats\x18\x07 \x01(\x08\x1a\x31\n\x10\x45ntryAccessesMsg\x12\x0c\n\x04keys\x18\x01 \x03(\x0c\x12\x0f\n\x07\x62\x61seRid\x18\x02 \x02(\x03\"r\n\x08\x45xecList\x12\x0b\n\x03rid\x18\x01 \x03(\x03\x12\x0e\n\x06\x62ranch\x18\x02 \x02(\x05\x12\r\n\x05start\x18\x03 \x02(\x08\x12\x12\n\nreplayMode\x18\x04 \x02(\t\x12\x12\n\ntargetHost\x18\x05 \x02(\t\x12\x12\n\ntargetPort\x18\x06 \x02(\x05\"P\n\x08ProxyMsg\x12\x0e\n\x06\x62ranch\x18\x01 \x01(\x05\x12\x10\n\x08restrain\x18\x02 \x01(\x08\x12\x12\n\ntimeTravel\x18\x03 \x01(\x03\x12\x0e\n\x06\x63ommit\x18\x04 \x01(\x03\x42)\n\x13pt.inesc.undo.protoB\x10\x46romManagerProtoH\x01')




_TODATANODE_ENTRYACCESSESMSG = _descriptor.Descriptor(
  name='EntryAccessesMsg',
  full_name='voldemort.ToDataNode.EntryAccessesMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='voldemort.ToDataNode.EntryAccessesMsg.keys', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseRid', full_name='voldemort.ToDataNode.EntryAccessesMsg.baseRid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=237,
  serialized_end=286,
)

_TODATANODE = _descriptor.Descriptor(
  name='ToDataNode',
  full_name='voldemort.ToDataNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newCommit', full_name='voldemort.ToDataNode.newCommit', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resetDependencies', full_name='voldemort.ToDataNode.resetDependencies', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redoOver', full_name='voldemort.ToDataNode.redoOver', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pathBranch', full_name='voldemort.ToDataNode.pathBranch', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pathCommit', full_name='voldemort.ToDataNode.pathCommit', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryAccessesMsg', full_name='voldemort.ToDataNode.entryAccessesMsg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='showStats', full_name='voldemort.ToDataNode.showStats', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TODATANODE_ENTRYACCESSESMSG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=286,
)


_EXECLIST = _descriptor.Descriptor(
  name='ExecList',
  full_name='voldemort.ExecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.ExecList.rid', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='branch', full_name='voldemort.ExecList.branch', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='voldemort.ExecList.start', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replayMode', full_name='voldemort.ExecList.replayMode', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetHost', full_name='voldemort.ExecList.targetHost', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetPort', full_name='voldemort.ExecList.targetPort', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=288,
  serialized_end=402,
)


_PROXYMSG = _descriptor.Descriptor(
  name='ProxyMsg',
  full_name='voldemort.ProxyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch', full_name='voldemort.ProxyMsg.branch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restrain', full_name='voldemort.ProxyMsg.restrain', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeTravel', full_name='voldemort.ProxyMsg.timeTravel', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commit', full_name='voldemort.ProxyMsg.commit', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=404,
  serialized_end=484,
)

_TODATANODE_ENTRYACCESSESMSG.containing_type = _TODATANODE;
_TODATANODE.fields_by_name['entryAccessesMsg'].message_type = _TODATANODE_ENTRYACCESSESMSG
DESCRIPTOR.message_types_by_name['ToDataNode'] = _TODATANODE
DESCRIPTOR.message_types_by_name['ExecList'] = _EXECLIST
DESCRIPTOR.message_types_by_name['ProxyMsg'] = _PROXYMSG

class ToDataNode(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class EntryAccessesMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TODATANODE_ENTRYACCESSESMSG

    # @@protoc_insertion_point(class_scope:voldemort.ToDataNode.EntryAccessesMsg)
  DESCRIPTOR = _TODATANODE

  # @@protoc_insertion_point(class_scope:voldemort.ToDataNode)

class ExecList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECLIST

  # @@protoc_insertion_point(class_scope:voldemort.ExecList)

class ProxyMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROXYMSG

  # @@protoc_insertion_point(class_scope:voldemort.ProxyMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023pt.inesc.undo.protoB\020FromManagerProtoH\001')
# @@protoc_insertion_point(module_scope)
