# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: from-manager.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='from-manager.proto',
  package='voldemort',
  serialized_pb='\n\x12\x66rom-manager.proto\x12\tvoldemort\"\x1c\n\x08Snapshot\x12\x10\n\x08seasonId\x18\x01 \x02(\x03\"\x17\n\x08\x45xecList\x12\x0b\n\x03rid\x18\x01 \x03(\x03\x42\x31\n\x1bvoldemort.undoTracker.protoB\x10\x46romManagerProtoH\x01')




_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='voldemort.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seasonId', full_name='voldemort.Snapshot.seasonId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=61,
)


_EXECLIST = _descriptor.Descriptor(
  name='ExecList',
  full_name='voldemort.ExecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.ExecList.rid', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['ExecList'] = _EXECLIST

class Snapshot(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SNAPSHOT

  # @@protoc_insertion_point(class_scope:voldemort.Snapshot)

class ExecList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECLIST

  # @@protoc_insertion_point(class_scope:voldemort.ExecList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\033voldemort.undoTracker.protoB\020FromManagerProtoH\001')
# @@protoc_insertion_point(module_scope)
