# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: to-manager.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='to-manager.proto',
  package='voldemort',
  serialized_pb='\n\x10to-manager.proto\x12\tvoldemort\"\xa0\x07\n\x0cMsgToManager\x12\x32\n\x08trackMsg\x18\x01 \x01(\x0b\x32 .voldemort.MsgToManager.TrackMsg\x12\x38\n\x0bstartEndMsg\x18\x02 \x01(\x0b\x32#.voldemort.MsgToManager.StartEndMsg\x12<\n\x12trackMsgFromClient\x18\x03 \x01(\x0b\x32 .voldemort.MsgToManager.TrackMsg\x12=\n\x0cnodeRegistry\x18\x04 \x01(\x0b\x32\'.voldemort.MsgToManager.NodeRegistryMsg\x12+\n\x03\x61\x63k\x18\x05 \x01(\x0b\x32\x1e.voldemort.MsgToManager.AckMsg\x12@\n\x0f\x65ntryAccessList\x18\x06 \x03(\x0b\x32\'.voldemort.MsgToManager.EntryAccessList\x12\x32\n\x08\x61\x63kProxy\x18\x07 \x01(\x0b\x32 .voldemort.MsgToManager.AckProxy\x1a+\n\x0f\x45ntryAccessList\x12\x0b\n\x03key\x18\x01 \x02(\x0c\x12\x0b\n\x03rid\x18\x02 \x03(\x03\x1aM\n\x08TrackMsg\x12\x31\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\".voldemort.MsgToManager.TrackEntry\x12\x0e\n\x06nodeId\x18\x02 \x01(\t\x1a-\n\nTrackEntry\x12\x0b\n\x03rid\x18\x01 \x02(\x03\x12\x12\n\ndependency\x18\x02 \x03(\x03\x1a\x1b\n\x0bStartEndMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x03\x1a\x34\n\x03SRD\x12\x0b\n\x03rid\x18\x01 \x01(\x03\x12\x0e\n\x06\x62ranch\x18\x02 \x01(\x05\x12\x10\n\x08restrain\x18\x03 \x01(\x08\x1a;\n\x06\x41\x63kMsg\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x11\n\texception\x18\x03 \x03(\t\x1a\x1d\n\x08\x41\x63kProxy\x12\x11\n\tcurrentId\x18\x01 \x02(\x03\x1a\xa7\x01\n\x0fNodeRegistryMsg\x12@\n\x05group\x18\x01 \x02(\x0e\x32\x31.voldemort.MsgToManager.NodeRegistryMsg.NodeGroup\x12\x0c\n\x04port\x18\x02 \x02(\x05\x12\x10\n\x08hostname\x18\x03 \x02(\t\"2\n\tNodeGroup\x12\t\n\x05PROXY\x10\x01\x12\x0b\n\x07\x44\x42_NODE\x10\x02\x12\r\n\tREDO_NODE\x10\x03\x42\'\n\x13pt.inesc.undo.protoB\x0eToManagerProtoH\x01')



_MSGTOMANAGER_NODEREGISTRYMSG_NODEGROUP = _descriptor.EnumDescriptor(
  name='NodeGroup',
  full_name='voldemort.MsgToManager.NodeRegistryMsg.NodeGroup',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROXY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DB_NODE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REDO_NODE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=910,
  serialized_end=960,
)


_MSGTOMANAGER_ENTRYACCESSLIST = _descriptor.Descriptor(
  name='EntryAccessList',
  full_name='voldemort.MsgToManager.EntryAccessList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='voldemort.MsgToManager.EntryAccessList.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.MsgToManager.EntryAccessList.rid', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=446,
  serialized_end=489,
)

_MSGTOMANAGER_TRACKMSG = _descriptor.Descriptor(
  name='TrackMsg',
  full_name='voldemort.MsgToManager.TrackMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='voldemort.MsgToManager.TrackMsg.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='voldemort.MsgToManager.TrackMsg.nodeId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=491,
  serialized_end=568,
)

_MSGTOMANAGER_TRACKENTRY = _descriptor.Descriptor(
  name='TrackEntry',
  full_name='voldemort.MsgToManager.TrackEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.MsgToManager.TrackEntry.rid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependency', full_name='voldemort.MsgToManager.TrackEntry.dependency', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=570,
  serialized_end=615,
)

_MSGTOMANAGER_STARTENDMSG = _descriptor.Descriptor(
  name='StartEndMsg',
  full_name='voldemort.MsgToManager.StartEndMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='voldemort.MsgToManager.StartEndMsg.data', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=617,
  serialized_end=644,
)

_MSGTOMANAGER_SRD = _descriptor.Descriptor(
  name='SRD',
  full_name='voldemort.MsgToManager.SRD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='voldemort.MsgToManager.SRD.rid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='branch', full_name='voldemort.MsgToManager.SRD.branch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restrain', full_name='voldemort.MsgToManager.SRD.restrain', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=646,
  serialized_end=698,
)

_MSGTOMANAGER_ACKMSG = _descriptor.Descriptor(
  name='AckMsg',
  full_name='voldemort.MsgToManager.AckMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='voldemort.MsgToManager.AckMsg.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='voldemort.MsgToManager.AckMsg.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exception', full_name='voldemort.MsgToManager.AckMsg.exception', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=700,
  serialized_end=759,
)

_MSGTOMANAGER_ACKPROXY = _descriptor.Descriptor(
  name='AckProxy',
  full_name='voldemort.MsgToManager.AckProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentId', full_name='voldemort.MsgToManager.AckProxy.currentId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=761,
  serialized_end=790,
)

_MSGTOMANAGER_NODEREGISTRYMSG = _descriptor.Descriptor(
  name='NodeRegistryMsg',
  full_name='voldemort.MsgToManager.NodeRegistryMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='voldemort.MsgToManager.NodeRegistryMsg.group', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='voldemort.MsgToManager.NodeRegistryMsg.port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='voldemort.MsgToManager.NodeRegistryMsg.hostname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSGTOMANAGER_NODEREGISTRYMSG_NODEGROUP,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=793,
  serialized_end=960,
)

_MSGTOMANAGER = _descriptor.Descriptor(
  name='MsgToManager',
  full_name='voldemort.MsgToManager',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackMsg', full_name='voldemort.MsgToManager.trackMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startEndMsg', full_name='voldemort.MsgToManager.startEndMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackMsgFromClient', full_name='voldemort.MsgToManager.trackMsgFromClient', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeRegistry', full_name='voldemort.MsgToManager.nodeRegistry', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='voldemort.MsgToManager.ack', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryAccessList', full_name='voldemort.MsgToManager.entryAccessList', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ackProxy', full_name='voldemort.MsgToManager.ackProxy', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MSGTOMANAGER_ENTRYACCESSLIST, _MSGTOMANAGER_TRACKMSG, _MSGTOMANAGER_TRACKENTRY, _MSGTOMANAGER_STARTENDMSG, _MSGTOMANAGER_SRD, _MSGTOMANAGER_ACKMSG, _MSGTOMANAGER_ACKPROXY, _MSGTOMANAGER_NODEREGISTRYMSG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=960,
)

_MSGTOMANAGER_ENTRYACCESSLIST.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_TRACKMSG.fields_by_name['entry'].message_type = _MSGTOMANAGER_TRACKENTRY
_MSGTOMANAGER_TRACKMSG.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_TRACKENTRY.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_STARTENDMSG.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_SRD.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_ACKMSG.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_ACKPROXY.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_NODEREGISTRYMSG.fields_by_name['group'].enum_type = _MSGTOMANAGER_NODEREGISTRYMSG_NODEGROUP
_MSGTOMANAGER_NODEREGISTRYMSG.containing_type = _MSGTOMANAGER;
_MSGTOMANAGER_NODEREGISTRYMSG_NODEGROUP.containing_type = _MSGTOMANAGER_NODEREGISTRYMSG;
_MSGTOMANAGER.fields_by_name['trackMsg'].message_type = _MSGTOMANAGER_TRACKMSG
_MSGTOMANAGER.fields_by_name['startEndMsg'].message_type = _MSGTOMANAGER_STARTENDMSG
_MSGTOMANAGER.fields_by_name['trackMsgFromClient'].message_type = _MSGTOMANAGER_TRACKMSG
_MSGTOMANAGER.fields_by_name['nodeRegistry'].message_type = _MSGTOMANAGER_NODEREGISTRYMSG
_MSGTOMANAGER.fields_by_name['ack'].message_type = _MSGTOMANAGER_ACKMSG
_MSGTOMANAGER.fields_by_name['entryAccessList'].message_type = _MSGTOMANAGER_ENTRYACCESSLIST
_MSGTOMANAGER.fields_by_name['ackProxy'].message_type = _MSGTOMANAGER_ACKPROXY
DESCRIPTOR.message_types_by_name['MsgToManager'] = _MSGTOMANAGER

class MsgToManager(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class EntryAccessList(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_ENTRYACCESSLIST

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.EntryAccessList)

  class TrackMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_TRACKMSG

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.TrackMsg)

  class TrackEntry(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_TRACKENTRY

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.TrackEntry)

  class StartEndMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_STARTENDMSG

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.StartEndMsg)

  class SRD(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_SRD

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.SRD)

  class AckMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_ACKMSG

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.AckMsg)

  class AckProxy(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_ACKPROXY

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.AckProxy)

  class NodeRegistryMsg(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSGTOMANAGER_NODEREGISTRYMSG

    # @@protoc_insertion_point(class_scope:voldemort.MsgToManager.NodeRegistryMsg)
  DESCRIPTOR = _MSGTOMANAGER

  # @@protoc_insertion_point(class_scope:voldemort.MsgToManager)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023pt.inesc.undo.protoB\016ToManagerProtoH\001')
# @@protoc_insertion_point(module_scope)
